# Welcome to Jekyll!
administrator:
  email: jan.louzek@pirati.cz, marek.krejpsky@pirati.cz
github:
  url: https://github.com/pirati-web/praha.pirati.cz/
  branch: master
url: "https://praha.pirati.cz"

mediaStorage: praha

title: Pirátská strana Praha
email: to@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://praha.pirati.cz" # the base hostname & protocol for your site

organization:
  name: Pirátská strana Praha
  shortName: Piráti Praha
  email: praha@pirati.cz
  phone: +420 703 681 682
  address: |
    Na Moráni 3,
    120 00 Praha 2
  mapLink: https://mapy.cz/s/norubuzado
  redmineLink: https://redmine.pirati.cz/projects/praha
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  donateLink: https://dary.pirati.cz/podpor-kraj/praha/  
  onboardingLink: https://nalodeni.pirati.cz/

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite

calendar:
  id: rm0h4oqjk2j2o0615sc4d1slfk@group.calendar.google.com
  title: "Pražský kalendář"
  page: "https://calendar.google.com/calendar/embed?src=rm0h4oqjk2j2o0615sc4d1slfk%40group.calendar.google.com&ctz=Europe%2FPrague"

facebook:
  loadSDK: true
  profilePage: "https://www.facebook.com/CeskaPiratskaStranaPraha/"
  profilePageName: "Piráti Praha"
  appId: 1526197851008996

matomo:
  loadSDK: true
  siteId: 68

forum:
  page: https://forum.pirati.cz/viewforum.php?f=78

youtube:
  channel: UC_zxYLGrkmrYazYt0MzyVlA

twitter:
  loadSDK: true
  profile: piratipraha

instagram:
  loadSDK: true
  profilePage: "https://instagram.com/piratipraha"

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

styleguide_base_url: 'https://styleguide.pirati.cz/latest'

############### SETTINSG #################

theme: jekyll-theme-pirati

# Build settings
markdown: kramdown
theme: jekyll-theme-pirati

pagination:
  per_page: 9
  permalink: '/:num/'
  title: ':title - stránka :num'
  trail: 7

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path:output_ext
  program:
    output: true
    permalink: /volby/:path:output_ext

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - profile
        - people
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - assets/js
    - assets/img
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-8.4.4/assets/img
